import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { db } from "../../utils/firebase.js";
import { collection, addDoc } from "firebase/firestore";
import { useState } from "react";

export default function Home() {
  const [placa, setPlaca] = useState("");
  const [endereco, setEndereco] = useState("");
  const [entregador, setEntregador] = useState("");
  const [saida, setSaida] = useState("");
  const [chegada, setChegada] = useState("");

  const addDemand = async () => {
    if (placa.length < 7) {
      alert("A placa precisa ter no mínimo 7 caracteres.");
      return;
    }
    try {
      const docRef = await addDoc(collection(db, "demandas"), {
        plate: placa.toUpperCase(),
        adress: endereco,
        name: entregador,
        exit: saida,
        arrive: chegada,

      });
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>AbreAi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <nav className="flex">
          <span className="material-icons text-3xl">navigate_before</span>
          <h1 className=" text-2xl font-medium ml-10">Cadastrar demanda</h1>
        </nav>
        <div>
          <input
            onChange={(e) => setEndereco(e.target.value)}
            className="w-4/5 border max-w-sm min-w-max border-gray-400 outline-none hover:border-green-400 rounded-xl mx-3 pl-5 py-2 mt-8"
            placeholder="Digite o endereço da entrega"
          ></input>
          <p className="pl-4">Nome do entregador</p>
          <input
            onChange={(e) => setEntregador(e.target.value)}
            className="w-4/5 max-w-sm min-w-max border border-gray-400 outline-none hover:border-green-400 rounded-xl mx-3 pl-5 py-2"
            placeholder="Ex: Luis Crisvaldo"
          ></input>
          <p className="pl-4">Placa do carro</p>
          <input
            onChange={(e) => setPlaca(e.target.value)}
            className="w-4/5 max-w-sm min-w-max border border-gray-400 outline-none hover:border-green-400 rounded-xl mx-3 pl-5 py-2 uppercase"
            placeholder="XXXXXXX"
          ></input>
          <div className="flex">
            <div>
              <p className="pl-4">Horario saída</p>
              <input
                onChange={(e) => setSaida(e.target.value)}
                className=" w-28 border border-gray-400 outline-none hover:border-green-400 rounded-xl mx-3 pl-5 py-2"
                placeholder="00:00"
              ></input>
            </div>
            <div>
              <p className="pl-4">Horario Chegada</p>
              <input
                onChange={(e) => setChegada(e.target.value)}
                className=" w-28 border border-gray-400 outline-none hover:border-green-400 rounded-xl mx-3 pl-5 py-2"
                placeholder="00:00"
              ></input>
            </div>
          </div>
        </div>
        <button
          onClick={() => addDemand()}
          className="w-4/5 max-w-sm min-w-max bg-[#349924] px-2 rounded-xl mt-2 mx-3 pl-5 py-2"
        >
          Finalizar
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
