import { db } from "../../utils/firebase.js";
import { collection, addDoc, getDocs } from "firebase/firestore";
import { useEffect, useState } from "react";
import Image from "next/image";
import logo from "../../assets/logoSem.svg";
import Head from "next/head";
import Modal from "../../components/modal.js";

export default function Dashboard() {
  const [demandas, setDemandas] = useState([]);
  const [modalDemand, setModalDemand] = useState({});
  const [showModal, setShowModal] = useState(false);

  const handleOpenModal = (demanda) => {
    setModalDemand(demanda);
    setShowModal(true);
    console.log(showModal, modalDemand);
  };

  const fetchData = async () => {
    const querySnapshot = await getDocs(collection(db, "demandas"));

    const lista = [];

    querySnapshot.forEach((doc) => {
      lista.push({ ...doc.data(), id: doc.id });
    });

    setDemandas(lista);
  };

  useEffect(() => {
    fetchData();
  }, []);

  return (
    <div>
      <Head>
        <title>AbreAi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>
      <main>
        <h1 className="ml-5 my-5 text-2xl font-medium">Dashboard</h1>
        <div className=" h-full">
          {demandas.map((demanda) => (
            <div
              onClick={() => handleOpenModal(demanda)}
              key={demanda.id}
              className={`cursor-pointer flex bg-gray-100 mx-5 mt-3 rounded-lg h-28 ${
                demanda.arrive
                  ? "border-l-8 border-green-600"
                  : "border-l-8 border-red-600"
              }`}
            >
              <Image className="ml-4" src={logo} alt="logo do abreai"></Image>
              <div className=" ml-4">
                <div className="mt-8 flex text-base">
                  <p className="font-bold">{demanda.exitPrevista} -</p>
                  <p className="font-bold ml-1">{demanda.arrivePrevista}</p>
                </div>
                <p className="">{demanda.address}</p>
              </div>{" "}
            </div>
          ))}
          <div className="flex h-full">
            <span
              onClick={() => (location.pathname = "demandas/cadastro")}
              className="text-green-500 material-icons text-6xl cursor-pointer bottom-10 right-7 absolute"
            >
              add_circle
            </span>
          </div>
        </div>
        <Modal
          show={showModal}
          demanda={modalDemand}
          onClose={() => setShowModal(false)}
        ></Modal>
      </main>
    </div>
  );
}
