import { db } from "../../utils/firebase.js";
import { collection, addDoc, getDocs } from "firebase/firestore";
import { useEffect, useState } from "react";
import Image from "next/image";
import logo from "../../public/logoSem.svg";
import Head from "next/head";
import Modal from "../../components/modal.js";

export default function Dashboard() {
  const [demandas, setDemandas] = useState([]);
  const [modalDemand, setModalDemand] = useState({});
  const [showModal, setShowModal] = useState(false);

  const handleOpenModal = (demanda) => {
    setModalDemand(demanda);
    setShowModal(true);
    console.log(showModal, modalDemand)
  };

  const fetchData = async () => {
    const querySnapshot = await getDocs(collection(db, "demandas"));

    const lista = [];
    const date = new Date().toLocaleTimeString();

    querySnapshot.forEach((doc) => {
      lista.push({ ...doc.data(), id: doc.id });
    });

    setDemandas(lista);
  };

  useEffect(() => {
    fetchData();
  }, []);
  return (
    <div>
      <Head>
        <title>AbreAi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>
      <main>
        <h1 className="ml-5 my-5 text-2xl font-medium">Dashboard</h1>
        <div>
          {demandas.map((demanda) => (
            <div
              key={demanda.id}
              className={`flex bg-gray-100 mx-5 mt-3 rounded-lg h-28 ${
                demanda.arrivePrevista <= demanda.arrive
                  ? "border-l-8 border-green-600"
                  : "border-l-8 border-red-600"
              }`}
            >
              <Image className="ml-4" src={logo} alt="logo do abreai"></Image>
              <div className=" ml-4">
                <div className="mt-8 flex text-base">
                  <p className="font-bold">{demanda.exitPrevista} -</p>
                  <p className="font-bold ml-1">{demanda.arrivePrevista}</p>
                </div>
                <p className="">{demanda.adress}</p>
              </div>
              <div
                onClick={() => handleOpenModal(demanda)}
                className="cursor-pointer ml-auto mt-3 mrc-3 material-icons text-2xl text-gray-400"
              >
                more_vert
              </div>
            </div>
          ))}
        </div>
        <Modal
          show={showModal}
          demanda={modalDemand}
          onClose={() => setShowModal(false)}
        ></Modal>
      </main>
    </div>
  );
}
