import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Menina from "../public/menina.svg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AbreAi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>

      <main className={` bgWpp ${styles.main}`}>
        <div className="text-center my-auto mb-4">
          <h1 className="font-inter font-semibold text-[#6B6458] text-2xl">
            Bem-vindo!
          </h1>
        </div>
        <div className="text-center mb-24">
          <p className="font-poppins text-sm font-normal mx-3">
            Agende a chegada de caminhões e carros de entregas ao terminal e
            registre a chegada!{" "}
          </p>
        </div>
        <button
          className="mb-1 font-normal text-xl text-white bg-[#349924] rounded-xl mx-8 px-4 py-4"
          onClick={() => (location.pathname = "demandas/cadastro")}
        >
          Cadastrar demanda
        </button>
        <div className="text-center mb-20">
          <span>Já possui alguma?</span>
          <a href="/demandas/dashboard" className=" text-[#349924] font-bold"> Veja aqui</a>
        </div>
      </main>
    </div>
  );
}
