import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Menina from "../public/menina.svg"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AbreAi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <Image
        src={Menina}
        alt="Picture of the author"
        ></Image>
        <h1>Bem-vindo!</h1>
        <p>
          Agende a chegada de caminhões e carros de entregas ao terminal e
          registre a chegada!{" "}
        </p>
        <button className="bg-[#349924] rounded-md" onClick={() => location.pathname = 'demandas/cadastro'}>Continuar</button>
        <div>
        <span>Já possui uma conta?</span>
        <span>Faça Login</span>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
